elastic/opbeans-node

- client/src/index.js
This is a requirement for sourcemapping to work correctly.
Note: this doesn't seem to be supported by the agent yet (or I use the wrong setting)
cc @jahtalab
> added serviceVersion

- README.md
- db/customer-ok.json
- db/customer-redos.json
- package.json
- server/routes.js
The purpose of this change is to allow us to introduce a delay in the response times on demand. The new `POST /api/customers` endpoint expects a body containing a new customer (in the form of a JSON document).
Here's an example JSON document for creating a new customer:
```json
{
"full_name": "Catherine Weaver",
"company_name": "Cyberdyne Systems",
"email": "cw@example.com",
"address": "18144 El Camino Real",
"postal_code": "5421",
"city": "Sunnyvale",
"country": "USA"
}
```
The code will validate that the e-mail is a valid e-mail using a regular expression. This regex however is vulnerable to a so called [ReDos](https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS) attack, so if you instead of a normal e-mail like `foo@example.com`, send up the string …
> feat: add POST /api/customers endpoint

- server.js
The headers and status code weren't getting proxied in `/api`.
> fix: proxy header forwarding

- worker.js
The worker is still using `apm.buildSpan` for creating custom spans, but this function got deprecated in the agent version `1.1.0`. After downloading `opbeans-node` and running `npm install` it installs an agent version that is greater than `1.1.0`, thus making the application fail as follows:
```{"level":50,"time":1542028790096,"msg":"apm.buildSpan is not a function","pid":2489,"hostname":"elastica.local","type":"Error","stack":"TypeError: apm.buildSpan is not a function\n    at performSubTask (/Users/andremm/tmp/opbeans-node/worker.js:63:18)\n    at performSubTasks (/Users/andremm/tmp/opbeans-node/worker.js:52:3)\n    at Timeout.processCompletedOrder (/Users/andremm/tmp/opbeans-node/worker.js:33:3)\n    at ontimeout (timers.js:424:11)\n    at tryOnTimeout (timers.js:288:5)\n    at …
```
> Fix worker to use startSpan instead of buildSpan

- server.js
Using `addTag` spams the logs with 4 extra lines per request
> fix: use addLabel instead of the deprecated addTag

- ecosystem-workload.config.js
Depends on elastic/apm-integration-testing#490
The apm-integration-testing project will set the `WORKLOAD_DISABLED` environment variable based on the `--no-opbeans-node-loadgen` command line flag.
> fix: allow workload script to be disabled

- .github/workflows/lint.yml
- .travis.yml
- README.md
- package.json
The main CI system used by this repo is Jenkins. Travis, and now GH
Actions, is only used for linting.
Refs: https://github.com/elastic/apm-agent-nodejs/issues/1922
> s/Travis CI/GitHub Actions

- README.md
- package-lock.json
- package.json
- server/config.js
The same effect can be had by manually using one of:
FOO=bar node ...
env `cat my.env` node ...
* * *
The argument is simplification. One less thing to know about and one less dependabot update to handle.
Currently the opbean-node server does:
```
if (env === 'development') {
require('dotenv').config()
env = process.env.NODE_ENV || env // in case dotenv changes NODE_ENV
}
```
which will add env vars from a ".env" file into the running `process.env`.  The same effect can be had by any of:
1. manually adding envvars:
```
FOO=bar npm run
env FOO=bar npm run
```
2. adding them from some file:
```
% cat my.env
FOO=bar
SPAM=eggs
% env `cat my.env` node -e 'console.log(process.env)' | tail -4
'/Library/Java/JavaVirtualMachines/jdk-15.0.1.jdk/Contents/Home',
_: '/usr/bin/env',
FOO: 'bar',
SPAM: …
```
> chore: drop dotenv devDependency and usage

- docker-compose-elastic-cloud.yml
- docker-compose.yml
The standard [node:12](https://github.com/nodejs/docker-node/blob/85ca3893867505ffbffbdf476722d3897fb3da98/12/stretch/Dockerfile) image uses Debian Stretch, which in turn references `postgresql-client` v9. This prevents the container tasked with initialising the database to use SCRAM authentication with Postgres >= 14. Debian Bullseye references `postgresql-client`, which suits our needs and fixes issue #129
- **Remove existing postgres volumes linked to opbeans-node** with `docker-compose down -v'
- Rebuild the project with `docker-compose up`
> Change the Node image used to init the database to Debian Bullseye

- .ci/bump-version.sh
- package-lock.json
https://github.com/elastic/opbeans-node/pull/72 added a package-lock.json to this repo to have repeatable versions.
However, the `.ci/bump-version.sh` that is run to bump the "elastic-apm-node" dependency version when a new release of the Node.js APM agent is tagged *does not commit changes to package-lock.json*.   The result is that we have a commit to the repo that *says* it has updated the elastic-apm-node dep (e.g. https://github.com/elastic/opbeans-node/commit/6ab7eba569a3b7126b1e65617320be888aaff893), but it won't actually use that newer version of the agent because package-lock.json hasn't been updated.
https://github.com/elastic/opbeans-node/pull/73 enabled dependabot on this repo. *That* will eventually create a PR to update the package-lock file. For example, in this case: …
> fix: bumping version should commit a changed package-lock.json

- .github/workflows/lint.yml
- .gitignore
This reinstates running of the  "lint" GitHub action on PRs and commits to main, broken when we changed the default branch from "master" to "main".
> fix lint workflow to work with 'main' branch

- .github/workflows/create-tag.yml
During the migration to GH Actions and upatecli in https://github.com/elastic/opbeans-node/pull/179, we forgot to replicate the behaviour of tagging the repository with the latest version.
This workflow runs on every push to `main`. If the version of `elastic-apm-node` already exists as tag, nothing will happen. Otherwise, it will create a new tag.
Closes #181
> Add create tag workflow

- .github/workflows/lint.yml
- Makefile
- docker-compose-elastic-cloud.yml
- docker-compose.yml
- package.json
Bumping engines to ">=14" because the opbeans-frontend is v14+ since
https://github.com/elastic/opbeans-frontend/pull/111
and there is little value in supporting older Node for this project.
Also bump v3 of actions/checkout and actions/setup-node to avoid this warning
in GH Actions CI:
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-node@v2.
> chore, ci: bump based supported node version to 14

- Dockerfile
Hi!
The Dockerfile placed at "Dockerfile" contains the best practice violation [DL3020](https://github.com/hadolint/hadolint/wiki/DL3020) detected by the [hadolint](https://github.com/hadolint/hadolint) tool.
The smell DL3020 occurs if ADD is used to copy files and directories that do not require tar self-extraction. In such cases, it is recommended to use the COPY instruction.
In this pull request, we propose a fix for that smell generated by our fixing tool. We have verified that the patch is correct before opening the pull request.
To fix this smell, specifically, the ADD instruction is replaced by an equivalent COPY instruction.
This change is only aimed at fixing that specific smell. If the fix is not valid or useful, please briefly indicate the reason and suggestions for possible …
> Fix for Dockerfile smell DL3020

- Dockerfile
- package-lock.json
- package.json
<Actions>
<action id="cb6dd7b45c4acf6e7e22dfdd30b9190defe5820ec706942b930759c7c9fdaaaf">
<h3>Bump elastic-apm-node to latest version</h3>
<details id="254db0fb64a77d55007f54b1cfb8c3dc722afb404e3dce28e3b46899bce3aacf">
<summary>Set org.label-schema.version in Dockerfile</summary>
<p>1 file(s) updated with &#34;org.label-schema.version=\&#34;4.2.0\&#34;&#34;:&#xA;&#x9;* Dockerfile&#xA;</p>
</details>
<details id="d79677188687e7b32b43de9d2365a1ff8ae6f1a9e3d494719be542394d99f7dd">
<summary>Install new elastic-apm-node npm dependency version</summary>
<p>ran shell command &#34;bash .ci/scripts/npm-install-elastic-apm-node.sh 4.2.0&#34;</p>
</details>
<a href="https://github.com/elastic/opbeans-node/actions/runs/6991100299">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr> …
> Bump elastic-apm-node to latest version

- .ci/bump-opbeans-node.yml
Condition returns 0 so it's always running even though if changes don't need to be applied.
Unfortunately, the existing shell targets are not idempotence therefore the condition is the gatekeeper. We could refactor the scripts to be idempotence as explained in the [target examples section](https://www.updatecli.io/docs/plugins/resource/shell/#_target_examples)
Given a feature branch based on `4.5.3`
```diff
diff --git a/.ci/bump-opbeans-node.yml b/.ci/bump-opbeans-node.yml
index 1ac32c4..083ad70 100644
--- a/.ci/bump-opbeans-node.yml
+++ b/.ci/bump-opbeans-node.yml
@@ -9,11 +9,11 @@ scms:
spec:
user: '{{ requiredEnv "GIT_USER" }}'
email: '{{ requiredEnv "GIT_EMAIL" }}'
-      owner: elastic
+      owner: v1v
repository: opbeans-node
token: '{{ requiredEnv "GITHUB_TOKEN" }}'
username: '{{ …
```
> updatecli: add reverse condition

- .ci/bump-opbeans-node.yml
Use the reverse logic
and https://github.com/elastic/opbeans-node/pull/264 was the outcome when running updatecli against this PR/branch
> updatecli: use reverse

- .github/workflows/bump-opbeans-node.yml
- .github/workflows/create-tag.yml
Use https://github.com/tibdex/github-app-token to generate ephemeral tokens so we can automate:
- Update CLI
- release automation
This is the alternative to moving away from finer-grained GitHub tokens and reducing the cumbersome of rotating them as we do nowadays.
We have used the same GitHub action in other places. I'm just trying the `permissions` flag to avoid using other permissions that require least-permissive access.
Release automation uses the ephemeral GitHub token generated by the GitHub action itself.
> ci: use ephemeral tokens with the required permissions

- .ci/updatecli/updatecli.d/bump-opbeans-node.yml
- .ci/updatecli/values.d/scm.yml
- .ci/updatecli/values.d/update-compose.yml
- .github/workflows/bump-opbeans-node.yml
- .github/workflows/updatecli.yml
- .tool-versions
- updatecli-compose.yaml
Pin `updatecli` version
Use updatecli policies to bump the updatecli version.
Use updatecli policies to bump the updatecli policies.
Use updatecli policies to run the local pipelines.
Let consumers choose what updatecli version should be used.
Automate the bump for the updatecli version
https://github.com/elastic/opbeans-node/actions/runs/12165477488 created
- https://github.com/elastic/opbeans-node/pull/295
- https://github.com/elastic/opbeans-node/pull/296
> feat: support updatecli compose and pin versions

- .github/CODEOWNERS
- .github/dependabot.yml
https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/
---
Same as was done in some other repos, e.g. https://github.com/elastic/elastic-otel-node/pull/795
> chore: use CODEOWNERS instead of 'reviewers' in dependabot.yml
